package com.w3foxes.sarah.ResumeDemo.resources;

import java.util.Optional;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.MediaType;

import com.codahale.metrics.annotation.Timed;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.w3foxes.sarah.ResumeDemo.api.Resume;

@Path("/resume")
@Produces(MediaType.APPLICATION_JSON)
public class ResumeResource {

	@GET
	@Timed
	public Resume getResume(@QueryParam("fileName") Optional<String> userId) {
		Resume resume = getResumeFromSomewhere();
		return resume;
	}
	
	// TODO: Move this data into the db and get it from there
	private Resume getResumeFromSomewhere() {
		ObjectMapper mapper = new ObjectMapper();
		Resume resume = new Resume();
		try {
			resume = mapper.readValue(resumeData, Resume.class);
		} catch (JsonMappingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (JsonProcessingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return resume;
	}
	
	private final String resumeData = "{\r\n"
			+ "	\"contactInfo\" : {\r\n"
			+ "		\"name\" : \"Sarah Fox\",\r\n"
			+ "		\"address\" : \" 4015 Brae Burn Dr., Eugene, OR 97405\",\r\n"
			+ "		\"phones\" : [\r\n"
			+ "			{ \"type\" : \"HOME\", \"number\" : \"541-343-1153\"},\r\n"
			+ "			{ \"type\" : \"MOBILE\", \"number\" : \"541-337-2452\"}\r\n"
			+ "		],\r\n"
			+ "		\"email\" : \"alienbaby42@gmail.com\"\r\n"
			+ "	},\r\n"
			+ "	\"education\" : [\r\n"
			+ "		{\"schoolName\": \"University of Oregon\",\r\n"
			+ "		 \"address\" : \"5257 University of Oregon, Eugene, OR 97403-5257\",\r\n"
			+ "		 \"degrees\" : [\"Bachelor of Science, 2000\"],\r\n"
			+ "		 \"majors\" : [\r\n"
			+ "		 	\"Computer and Information Science\",\r\n"
			+ "		 	\"Mathematics\"\r\n"
			+ "		 ],\r\n"
			+ "		 \"awards\" : [\r\n"
			+ "		 	\"Phi Beta Kappa\",\r\n"
			+ "		 	\"Magna Cum Laude\"\r\n"
			+ "		 ]\r\n"
			+ "		}\r\n"
			+ "	],\r\n"
			+ "	\"skills\" :[\r\n"
			+ "		{ \"category\" : \"Java\",\r\n"
			+ "		  \"name\": \"Java\",\r\n"
			+ "		  \"proficiency\" : \"HIGH\"},\r\n"
			+ "		{ \"category\" : \"Java\",\r\n"
			+ "		  \"name\": \"Dropwizard\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"},\r\n"
			+ "		{ \"category\" : \"Java\",\r\n"
			+ "		  \"name\": \"JUnit\",\r\n"
			+ "		  \"proficiency\" : \"HIGH\"},\r\n"
			+ "		{ \"category\" : \"Java\",\r\n"
			+ "		  \"name\": \"Seam\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"},\r\n"
			+ "		{ \"category\" : \"Java\",\r\n"
			+ "		  \"name\": \"Struts\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"},\r\n"
			+ "		{ \"category\" : \"Java\",\r\n"
			+ "		  \"name\": \"JSP\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"},\r\n"
			+ "		{ \"category\" : \"Java\",\r\n"
			+ "		  \"name\": \"JSTL\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"},\r\n"
			+ "		{ \"category\" : \"Java\",\r\n"
			+ "		  \"name\": \"Selenium\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"},\r\n"
			+ "\r\n"
			+ "		{ \"category\" : \"Build Systems\",\r\n"
			+ "		  \"name\": \"Gradle\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"},\r\n"
			+ "		{ \"category\" : \"Build Systems\",\r\n"
			+ "		  \"name\": \"Ant\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"},\r\n"
			+ "		{ \"category\" : \"Build Systems\",\r\n"
			+ "		  \"name\": \"Maven\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"},\r\n"
			+ "		{ \"category\" : \"Build Systems\",\r\n"
			+ "		  \"name\": \"Hudson/Jenkins\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"},\r\n"
			+ "\r\n"
			+ "		{ \"category\" : \"Database\",\r\n"
			+ "		  \"name\": \"Hibernate\",\r\n"
			+ "		  \"proficiency\" : \"HIGH\"},\r\n"
			+ "		{ \"category\" : \"Database\",\r\n"
			+ "		  \"name\": \"Liquibase\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"},\r\n"
			+ "		{ \"category\" : \"Database\",\r\n"
			+ "		  \"name\": \"Postgres\",\r\n"
			+ "		  \"proficiency\" : \"HIGH\"},\r\n"
			+ "		{ \"category\" : \"Database\",\r\n"
			+ "		  \"name\": \"MSSQL\",\r\n"
			+ "		  \"proficiency\" : \"OBSOLETE\"},\r\n"
			+ "		{ \"category\" : \"Database\",\r\n"
			+ "		  \"name\": \"MySQL\",\r\n"
			+ "		  \"proficiency\" : \"OBSOLETE\"},\r\n"
			+ "\r\n"
			+ "		{ \"category\" : \"Javascript\",\r\n"
			+ "		  \"name\": \"Javascript\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"},\r\n"
			+ "		{ \"category\" : \"Javascript\",\r\n"
			+ "		  \"name\": \"React\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"},\r\n"
			+ "		{ \"category\" : \"Javascript\",\r\n"
			+ "		  \"name\": \"Backbone\",\r\n"
			+ "		  \"proficiency\" : \"LOW\"},\r\n"
			+ "		{ \"category\" : \"Javascript\",\r\n"
			+ "		  \"name\": \"Handlebars\",\r\n"
			+ "		  \"proficiency\" : \"LOW\"},\r\n"
			+ "		{ \"category\" : \"Javascript\",\r\n"
			+ "		  \"name\": \"Underscore\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"},\r\n"
			+ "		{ \"category\" : \"Javascript\",\r\n"
			+ "		  \"name\": \"Jquery\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"},\r\n"
			+ "		{ \"category\" : \"Javascript\",\r\n"
			+ "		  \"name\": \"Jasmine\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"},\r\n"
			+ "\r\n"
			+ "		{ \"category\" : \"OS\",\r\n"
			+ "		  \"name\": \"Docker\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"},\r\n"
			+ "		{ \"category\" : \"OS\",\r\n"
			+ "		  \"name\": \"Vagrant\",\r\n"
			+ "		  \"proficiency\" : \"LOW\"},\r\n"
			+ "		{ \"category\" : \"OS\",\r\n"
			+ "		  \"name\": \"Mac\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"},\r\n"
			+ "		{ \"category\" : \"OS\",\r\n"
			+ "		  \"name\": \"Windows\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"},\r\n"
			+ "		{ \"category\" : \"OS\",\r\n"
			+ "		  \"name\": \"Linux\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"},\r\n"
			+ "\r\n"
			+ "		{ \"category\" : \"Other Languages\",\r\n"
			+ "		  \"name\": \"Ruby\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"},\r\n"
			+ "		{ \"category\" : \"Other Languages\",\r\n"
			+ "		  \"name\": \"Classic ASP\",\r\n"
			+ "		  \"proficiency\" : \"LOW\"},\r\n"
			+ "		{ \"category\" : \"Other Languages\",\r\n"
			+ "		  \"name\": \"ASP.NET\",\r\n"
			+ "		  \"proficiency\" : \"LOW\"},\r\n"
			+ "		{ \"category\" : \"Other Languages\",\r\n"
			+ "		  \"name\": \"VB.NET\",\r\n"
			+ "		  \"proficiency\" : \"LOW\"},\r\n"
			+ "		{ \"category\" : \"Other Languages\",\r\n"
			+ "		  \"name\": \"C#\",\r\n"
			+ "		  \"proficiency\" : \"LOW\"},\r\n"
			+ "		{ \"category\" : \"Other Languages\",\r\n"
			+ "		  \"name\": \"C++\",\r\n"
			+ "		  \"proficiency\" : \"OBSOLETE\"},\r\n"
			+ "		{ \"category\" : \"Other Languages\",\r\n"
			+ "		  \"name\": \"Python\",\r\n"
			+ "		  \"proficiency\" : \"OBSOLETE\"},\r\n"
			+ "\r\n"
			+ "		{ \"category\" : \"Web\",\r\n"
			+ "		  \"name\": \"HTML\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"},\r\n"
			+ "		{ \"category\" : \"Web\",\r\n"
			+ "		  \"name\": \"XML\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"},\r\n"
			+ "		{ \"category\" : \"Web\",\r\n"
			+ "		  \"name\": \"XSL\",\r\n"
			+ "		  \"proficiency\" : \"LOW\"},\r\n"
			+ "		{ \"category\" : \"Web\",\r\n"
			+ "		  \"name\": \"CSS\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"},\r\n"
			+ "		{ \"category\" : \"Web\",\r\n"
			+ "		  \"name\": \"LESS\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"},\r\n"
			+ "\r\n"
			+ "		{ \"category\" : \"Version Control\",\r\n"
			+ "		  \"name\": \"Git\",\r\n"
			+ "		  \"proficiency\" : \"HIGH\"},\r\n"
			+ "		{ \"category\" : \"Version Control\",\r\n"
			+ "		  \"name\": \"SVN\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"},\r\n"
			+ "		{ \"category\" : \"Version Control\",\r\n"
			+ "		  \"name\": \"CVS\",\r\n"
			+ "		  \"proficiency\" : \"LOW\"},\r\n"
			+ "		  \r\n"
			+ "		{ \"category\" : \"Bug Reporting\",\r\n"
			+ "		  \"name\": \"Jira\",\r\n"
			+ "		  \"proficiency\" : \"HIGH\"},\r\n"
			+ "		{ \"category\" : \"Bug Reporting\",\r\n"
			+ "		  \"name\": \"FogBugs\",\r\n"
			+ "		  \"proficiency\" : \"LOW\"},\r\n"
			+ "		  \r\n"
			+ "		{ \"category\" : \"IDE\",\r\n"
			+ "		  \"name\": \"Eclipse\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"},\r\n"
			+ "		{ \"category\" : \"IDE\",\r\n"
			+ "		  \"name\": \"Visual Studio\",\r\n"
			+ "		  \"proficiency\" : \"LOW\"},\r\n"
			+ "		  \r\n"
			+ "		{ \"category\" : \"Methodologies\",\r\n"
			+ "		  \"name\": \"Agile\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"},\r\n"
			+ "		{ \"category\" : \"Methodologies\",\r\n"
			+ "		  \"name\": \"SCRUM\",\r\n"
			+ "		  \"proficiency\" : \"MEDIUM\"}\r\n"
			+ "	],\r\n"
			+ "	\"jobs\" : [\r\n"
			+ "		{\r\n"
			+ "			\"dates\": \"November 2020 - present\",\r\n"
			+ "			\"employer\" : \"Personal Projects\",\r\n"
			+ "			\"titles\" : [],\r\n"
			+ "			\"tasks\": [\r\n"
			+ "				\"Started development on a web app for pilots.  Set up the initial framework with Dropwizard and React.  Learned to use the Maven build system for the project.  Wrote specs, examined business case, and decided to shelve project.\",\r\n"
			+ "				\"Assisted with spouse’s art business.  Assembled, sanded, and painted picture frames and display panels.  Worked the booth at art shows.\"\r\n"
			+ "			]\r\n"
			+ "		},\r\n"
			+ "		{\r\n"
			+ "			\"dates\": \"July 2011 - October 2020\",\r\n"
			+ "			\"employer\" : \"Palo Alto Software\",\r\n"
			+ "			\"titles\" : [\"Software Developer\"],\r\n"
			+ "			\"tasks\": [\r\n"
			+ "				\"Maintained the LivePlan application, a large business planning webapp.  Implemented new features, fixed bugs, wrote and maintained unit tests.  Wrote extensive documentation.  Learned new technologies as needed.  Did code reviews.\",\r\n"
			+ "				\"Helped transition app from a Struts/SEAM/JSP architecture to a Dropwizard/React architecture.\",\r\n"
			+ "				\"Researched how to write database updates for zero-downtime deployments.  Wrote documentation for the rest of the department to use.\",\r\n"
			+ "				\"Joined the LiveWell committee which helped plan events for employee health/wellness/morale. Mentored new employees.\"\r\n"
			+ "			]\r\n"
			+ "		},\r\n"
			+ "		{\r\n"
			+ "			\"dates\": \"June 2003 - June 2011\",\r\n"
			+ "			\"employer\" : \"Avant Assessment\",\r\n"
			+ "			\"titles\" : [\"Programmer (2003 - 2008)\", \"Senior Software Developer (2008 - 2010)\", \"Software Engineer (2010 - 2011)\"],\r\n"
			+ "			\"tasks\": [\r\n"
			+ "				\"Won Ed Knapp Award in December 2009. &quot;Awarded to Sarah Fox for her consistent and laser-like determination to accomplish any task given to her with dispatch and the highest quality of workmanship.&quot;\",\r\n"
			+ "				\"Created and maintained a large Java/Struts based item development and test-delivery system, as well as maintaining several classic ASP applications.\",\r\n"
			+ "				\"Created a new ASP.NET webapp to save the sales department hundreds of hours of data-entry work.\",\r\n"
			+ "				\"Mentored junior developers.\",\r\n"
			+ "				\"Reviewed code of other developers.\",\r\n"
			+ "				\"Wrote specifications, technical documentation, and user documentation.\",\r\n"
			+ "				\"Learned new technologies as needed.  Took classes in: C#, VB.NET, ASP.NET, and Writing User Requirement Docs.  Learned Spring and Hibernate on the job.\"\r\n"
			+ "			]\r\n"
			+ "		},\r\n"
			+ "		{\r\n"
			+ "			\"dates\": \"August 2004 - December 2004, April 2005, November 2005\",\r\n"
			+ "			\"employer\" : \"University of Oregon, Center for Applied Second Language Studies (CASLS)\",\r\n"
			+ "			\"titles\" : [\"Software Developer\"],\r\n"
			+ "			\"tasks\": [\r\n"
			+ "				\"Designed and wrote a Java/Struts based item development and test-delivery system, which was then licensed to Avant Assessment.\",\r\n"
			+ "				\"Returned in April and November to add additional features to the system.\"\r\n"
			+ "			]\r\n"
			+ "		},\r\n"
			+ "		{\r\n"
			+ "			\"dates\": \"October 2003 - June 2005\",\r\n"
			+ "			\"employer\" : \"Business English Language Learning Solutions (BELLS)\",\r\n"
			+ "			\"titles\" : [\"Software Developer\", \"Voice-over Artist\"],\r\n"
			+ "			\"tasks\": [\r\n"
			+ "				\"Worked on new features for a Java/Struts based language learning application.\",\r\n"
			+ "				\"Recorded and edited English voice-overs for daily lessons.\"\r\n"
			+ "			]\r\n"
			+ "		},\r\n"
			+ "		{\r\n"
			+ "			\"dates\": \"2000 - 2003\",\r\n"
			+ "			\"employer\" : \"Counterclaim\",\r\n"
			+ "			\"titles\" : [\"Programmer\"],\r\n"
			+ "			\"tasks\": [\r\n"
			+ "				\"Worked on a Java/Struts based webapp for electronic filing of court documents and a Java based case management webapp.\"\r\n"
			+ "			]\r\n"
			+ "		}\r\n"
			+ "	],\r\n"
			+ "	\"recommendations\": [\r\n"
			+ "		{\r\n"
			+ "		\"by\": \"Laurence Gellert\",\r\n"
			+ "		\"title\": \"Chief Software Architect, Avant Assessment\",\r\n"
			+ "		\"text\": \"When we first interviewed Sarah, we realized in under a minute - she was born to work with software.  Of course we immediately hired her and it worked out great!  Sarah has amazing talents when it comes to the language of computers.  She is truly one of Joel of Software's 10x coders in terms of productivity.  In the seven years of working together I saw Sarah pick up many new concepts and meld them into her approach.  These include key contributions in refining our products to run virtually bug free.  Analytical skills - outstanding.  Code readability - top notch, very gifted in this area.  Believes in writing code comments!  Good memory.  Practical judgment when considering technology tradeoffs.\"\r\n"
			+ "		},\r\n"
			+ "		{\r\n"
			+ "			\"by\" : \"Junko Hirayama\",\r\n"
			+ "			\"title\" : \"Programmer, Avant Assessment, LLC\",\r\n"
			+ "			\"text\": \"I had the pleasure of working with Sarah at Avant Assessment for nearly 4 years.  She is a highly skilled and versatile programmer.  She has shown excellence in her work through detail and always be a responsible and dedicated worker.  She is a great team player to work with and makes sure that her work in completed on time.  We depended on her knowledge about most of our products.  Also, she is a great team mate to share new technology and to influence each other.  I would highly recommend Sarah Fox to anyone looking for a loyal, hard working, highly skilled IT team member.\"\r\n"
			+ "		}\r\n"
			+ "	],\r\n"
			+ "	\"references\": [\r\n"
			+ "		{\r\n"
			+ "			\"who\": \"Carol Buie\",\r\n"
			+ "			\"title\": \"Business Analyst, Avant Assessment\",\r\n"
			+ "			\"email\": \"carol.buie@gmail.com\",\r\n"
			+ "			\"phone\": {\"type\": \"MOBILE\", \"number\": \"541-221-9979\"},\r\n"
			+ "			\"status\": \"ARCHIVE\"\r\n"
			+ "		},\r\n"
			+ "		{\r\n"
			+ "			\"who\": \"Melissa Pohlman\",\r\n"
			+ "			\"title\": \"QA Engineer, Avant Assessment\",\r\n"
			+ "			\"email\": \"melissa_pohlman@yahoo.com\",\r\n"
			+ "			\"status\": \"ARCHIVE\"\r\n"
			+ "		},\r\n"
			+ "		{\r\n"
			+ "			\"who\": \"Laurence Gellert\",\r\n"
			+ "			\"title\": \"Educational Software Architect, University of Oregon, CASLS\",\r\n"
			+ "			\"email\": \"gellert@uoregon.edu\",\r\n"
			+ "			\"phone\": {\"type\": \"HOME\", \"number\": \"503-442-8705\"},\r\n"
			+ "			\"status\": \"ARCHIVE\"\r\n"
			+ "		},\r\n"
			+ "		{\r\n"
			+ "			\"who\": \"Adam Becker\",\r\n"
			+ "			\"title\": \"Manager at Palo Alto Software\",\r\n"
			+ "			\"email\": \"adamcbecker@gmail.com\",\r\n"
			+ "			\"phone\": {\"type\": \"MOBILE\", \"number\": \"503-810-0127\"},\r\n"
			+ "			\"status\": \"CURRENT\"\r\n"
			+ "		},\r\n"
			+ "		{\r\n"
			+ "			\"who\": \"Evan Coonrod\",\r\n"
			+ "			\"title\": \"Coworker at Palo Alto Software\",\r\n"
			+ "			\"email\": \"evan@coonrod.org\",\r\n"
			+ "			\"phone\": {\"type\": \"MOBILE\", \"number\": \"541-953-1123\"},\r\n"
			+ "			\"status\": \"CURRENT\"\r\n"
			+ "		},\r\n"
			+ "		{\r\n"
			+ "			\"who\": \"Xiangkui Yao\",\r\n"
			+ "			\"title\": \"Coworker at Palo Alto Software\",\r\n"
			+ "			\"email\": \"x.yao.76@gmail.com\",\r\n"
			+ "			\"phone\": {\"type\": \"MOBILE\", \"number\": \"541-683-3757\"},\r\n"
			+ "			\"status\": \"CURRENT\"\r\n"
			+ "		}\r\n"
			+ "	]\r\n"
			+ "}";
	
}
